field.formatter.settings.media_remote_illinois_mediaspace:
  type: mapping
  label: 'Mediaspace display format settings'
  mapping:
    formatter_class:
      type: string
      label: 'Formatter class name'
    width:
      type: string
      label: 'Iframe width'
    height:
      type: string
      label: 'Iframe height'
