<?php
/**
 * Implements hook_install().
 */
function illinois_framework_core_trash_admin_install() {
  \Drupal::configFactory()
    ->getEditable('trash.settings')
    ->set('enabled_entity_types', [
      'node' => [],
      'path_alias' => [],
      'menu_link_content' => [],
      'media' => [],
      'taxonomy_term' => [],
    ])
    ->set('auto_purge.enabled', TRUE)
    ->set('auto_purge.after', '365 days')
    ->save();
}
