#To edit see https://github.com/marketplace/actions/create-issue-branch
name: issues and project

on:
    issues:
        types: [assigned]
jobs:
  create-issue-branch:
    name: "create issue branch"
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@v1.5
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
